<!DOCTYPE html>
<html>
<?php include('includes/head.php'); ?>

<body class="d-flex vh-100 flex-column justify-content-between">
    <?php include('includes/header.php'); ?>

    <main role="main" class="container">
        <h1>Zone secrête</h1>
        <div class="jumbotron">
            <form>
                <div class="form-group">
                    <label>Langage favori</label>
                    <select id="language" class="form-control">
                        <option name="0">A+</option>
                        <option name="1">A++</option>
                        <option name="2">A# .NET</option>
                        <option name="3">A# (Axiom)</option>
                        <option name="4">A-0 System</option>
                        <option name="5">ABAL</option>
                        <option name="6">ABAL++</option>
                        <option name="7">ABAP</option>
                        <option name="8">ABC</option>
                        <option name="9">ABCL/1</option>
                        <option name="10">ABCL/c+</option>
                        <option name="11">ABCL/R</option>
                        <option name="12">ABCL/R2</option>
                        <option name="13">Abel</option>
                        <option name="14">ABSET</option>
                        <option name="15">ABSYS</option>
                        <option name="16">ALI</option>
                        <option name="17">Abundance</option>
                        <option name="18">ACC</option>
                        <option name="19">Accent</option>
                        <option name="20">ActForex</option>
                        <option name="21">Ace DASL</option>
                        <option name="22">ACT-III</option>
                        <option name="23">Ada</option>
                        <option name="24">Adenine</option>
                        <option name="25">Afnix</option>
                        <option name="26">Agora</option>
                        <option name="27">AIS Balise</option>
                        <option name="28">Aikido</option>
                        <option name="29">Alef</option>
                        <option name="30">Algebraic Logic Functional programming language</option>
                        <option name="31">Algol 60</option>
                        <option name="32">Algol 68</option>
                        <option name="33">Algol W</option>
                        <option name="34">Alice</option>
                        <option name="35">Ambi</option>
                        <option name="36">Amiga E</option>
                        <option name="37">AML</option>
                        <option name="38">AMOS</option>
                        <option name="39">AMPLE</option>
                        <option name="40">Anubis</option>
                        <option name="41">APDL</option>
                        <option name="42">APL</option>
                        <option name="43">AppleScript</option>
                        <option name="44">Arc</option>
                        <option name="45">Ariberion</option>
                        <option name="46">Arobase (langage)</option>
                        <option name="47">Assembleur</option>
                        <option name="48">ASP.NET</option>
                        <option name="49">ATS</option>
                        <option name="50">AutoHotkey</option>
                        <option name="51">AutoIt</option>
                        <option name="52">Averest</option>
                        <option name="53">awk</option>
                        <option name="54">axe parser</option>
                        <option name="55">Axum</option>
                        <option name="56">B</option>
                        <option name="57">BASIC</option>
                        <option name="58">BASICA</option>
                        <option name="59">BlitzBasic</option>
                        <option name="60">DarkBasic</option>
                        <option name="61">FreeBasic</option>
                        <option name="62">GW-Basic</option>
                        <option name="63">Microsoft Small Basic</option>
                        <option name="64">PowerBasic</option>
                        <option name="65">PureBasic</option>
                        <option name="66">QuickBasic</option>
                        <option name="67">SmallBasic</option>
                        <option name="68">TI-Basic</option>
                        <option name="69">True Basic</option>
                        <option name="70">Turbo Basic</option>
                        <option name="71">Visual Basic</option>
                        <option name="72">wxBasic</option>
                        <option name="73">Bash (Bourne-Again shell)</option>
                        <option name="74">Batch file (fichier bat)</option>
                        <option name="75">bc</option>
                        <option name="76">BCPL</option>
                        <option name="77">BeanShell</option>
                        <option name="78">Befunge</option>
                        <option name="79">Bennu</option>
                        <option name="80">Bertrand</option>
                        <option name="81">BETA</option>
                        <option name="82">Bigwig</option>
                        <option name="83">Bistro</option>
                        <option name="84">BitC</option>
                        <option name="85">BLISS</option>
                        <option name="86">BlitzBasic</option>
                        <option name="87">Blueprint Visual Scripting</option>
                        <option name="88">Blue</option>
                        <option name="89">Bon</option>
                        <option name="90">Boo</option>
                        <option name="91">Boomerang</option>
                        <option name="92">Bosque</option>
                        <option name="93">Bourne shell (sh)</option>
                        <option name="94">BPEL</option>
                        <option name="95">Brainfuck</option>
                        <option name="96">BUGSYS</option>
                        <option name="97">BuildProfessional</option>
                        <option name="98">C</option>
                        <option name="99">C--</option>
                        <option name="100">C++</option>
                        <option name="101">C#</option>
                        <option name="102">C/AL</option>
                        <option name="103">Caché ObjectScript</option>
                        <option name="104">Cameleon</option>
                        <option name="105">Caml</option>
                        <option name="106">Cat</option>
                        <option name="107">Cayenne</option>
                        <option name="108">Cecil</option>
                        <option name="109">Cel</option>
                        <option name="110">Cesil</option>
                        <option name="111">Ceylon</option>
                        <option name="112">CFML</option>
                        <option name="113">Cg</option>
                        <option name="114">Ch interpreter</option>
                        <option name="115">Chapel</option>
                        <option name="116">CHAIN</option>
                        <option name="117">Charity</option>
                        <option name="118">Chef</option>
                        <option name="119">CHILL</option>
                        <option name="120">CHIP-8</option>
                        <option name="121">chomski</option>
                        <option name="122">CHR</option>
                        <option name="123">Chrome</option>
                        <option name="124">ChucK</option>
                        <option name="125">CICODE</option>
                        <option name="126">CIL</option>
                        <option name="127">Cilk</option>
                        <option name="128">CL</option>
                        <option name="129">Claire</option>
                        <option name="130">Clarion</option>
                        <option name="131">Clean</option>
                        <option name="132">Clipper</option>
                        <option name="133">CLIST</option>
                        <option name="134">Clojure</option>
                        <option name="135">CLU</option>
                        <option name="136">CMS-2</option>
                        <option name="137">COBOL</option>
                        <option name="138">CobolScript</option>
                        <option name="139">Cobra</option>
                        <option name="140">CODE</option>
                        <option name="141">CoffeeScript</option>
                        <option name="142">Cola</option>
                        <option name="143">ColdC</option>
                        <option name="144">ColdFusion</option>
                        <option name="145">COMAL</option>
                        <option name="146">Common Lisp</option>
                        <option name="147">COMPASS</option>
                        <option name="148">Component Pascal</option>
                        <option name="149">COMIT</option>
                        <option name="150">Converge</option>
                        <option name="151">Cool</option>
                        <option name="152">Coq</option>
                        <option name="153">Coral 66</option>
                        <option name="154">Corn</option>
                        <option name="155">CorVision</option>
                        <option name="156">Cosmos-f</option>
                        <option name="157">COWSEL</option>
                        <option name="158">CPL</option>
                        <option name="159">Crystal</option>
                        <option name="160">C shell (csh)</option>
                        <option name="161">CSP</option>
                        <option name="162">Csound</option>
                        <option name="163">CSS</option>
                        <option name="164">CSS 3</option>
                        <option name="165">Cubescript</option>
                        <option name="166">Curl</option>
                        <option name="167">Curry</option>
                        <option name="168">Cyclone</option>
                        <option name="169">D</option>
                        <option name="170">DaKeoZ</option>
                        <option name="171">Dao</option>
                        <option name="172">DASL - Distributed Application Specification Language</option>
                        <option name="173">DASL - Datapoint's Advanced Systems Language</option>
                        <option name="174">DarkBASIC</option>
                        <option name="175">Dart</option>
                        <option name="176">DataFlex</option>
                        <option name="177">Datalog</option>
                        <option name="178">dBase</option>
                        <option name="179">dc</option>
                        <option name="180">DCL</option>
                        <option name="181">Deesel</option>
                        <option name="182">G</option>
                        <option name="183">Delphi</option>
                        <option name="184">Dialect</option>
                        <option name="185">DinkC</option>
                        <option name="186">Dialog Manager</option>
                        <option name="187">DIBOL</option>
                        <option name="188">Down</option>
                        <option name="189">Duke C</option>
                        <option name="190">Dylan</option>
                        <option name="191">Dynace</option>
                        <option name="192">E</option>
                        <option name="193">Ease</option>
                        <option name="194">EASY</option>
                        <option name="195">Easytrieve Classic</option>
                        <option name="196">Easytrieve Plus</option>
                        <option name="197">eC (Ecere C)</option>
                        <option name="198">ECMAScript</option>
                        <option name="199">eDeveloper</option>
                        <option name="200">Edinburgh IMP</option>
                        <option name="201">EGL</option>
                        <option name="202">Eiffel</option>
                        <option name="203">Einstein</option>
                        <option name="204">Elan</option>
                        <option name="205">elastiC</option>
                        <option name="206">Elf</option>
                        <option name="207">Emacs Lisp</option>
                        <option name="208">Englesi</option>
                        <option name="209">Epigram</option>
                        <option name="210">Erlang</option>
                        <option name="211">Escapade</option>
                        <option name="212">Escher</option>
                        <option name="213">Esterel</option>
                        <option name="214">Etoys</option>
                        <option name="215">Euclid</option>
                        <option name="216">Euler</option>
                        <option name="217">Euphoria</option>
                        <option name="218">CMS EXEC</option>
                        <option name="219">EXEC 2</option>
                        <option name="220">Extends</option>
                        <option name="221">F</option>
                        <option name="222">F#</option>
                        <option name="223">Factor</option>
                        <option name="224">Falcon</option>
                        <option name="225">False</option>
                        <option name="226">Fan</option>
                        <option name="227">Fancy</option>
                        <option name="228">Fantom</option>
                        <option name="229">FAUST</option>
                        <option name="230">Felix</option>
                        <option name="231">Ferite</option>
                        <option name="232">FFP</option>
                        <option name="233">Fjölnir</option>
                        <option name="234">FL</option>
                        <option name="235">Flavors</option>
                        <option name="236">FLOW-MATIC</option>
                        <option name="237">Fly</option>
                        <option name="238">FOCAL</option>
                        <option name="239">FOCUS</option>
                        <option name="240">FOIL</option>
                        <option name="241">FORMAC</option>
                        <option name="242">@Formula</option>
                        <option name="243">Forth</option>
                        <option name="244">Fortran</option>
                        <option name="245">Fortress</option>
                        <option name="246">FoxPro 2</option>
                        <option name="247">FP</option>
                        <option name="248">Franz Lisp</option>
                        <option name="249">F-Script</option>
                        <option name="250">FSProg</option>
                        <option name="251">Funnel</option>
                        <option name="252">Fuxi</option>
                        <option name="253">Gambas</option>
                        <option name="254">GAMS</option>
                        <option name="255">GAP (RGP)</option>
                        <option name="256">GAP (logiciel de calcul formel)</option>
                        <option name="257">G-code</option>
                        <option name="258">GDL</option>
                        <option name="259">Gibiane</option>
                        <option name="260">GFA BASIC</option>
                        <option name="261">GJ</option>
                        <option name="262">GLSL</option>
                        <option name="263">GM</option>
                        <option name="264">GML (Game Maker Language)</option>
                        <option name="265">Go</option>
                        <option name="266">Go!</option>
                        <option name="267">GOAL</option>
                        <option name="268">GDScript</option>
                        <option name="269">Gödel</option>
                        <option name="270">Godiva</option>
                        <option name="271">Goo</option>
                        <option name="272">GOTO++</option>
                        <option name="273">GOTRAN</option>
                        <option name="274">GPSS</option>
                        <option name="275">GraphTalk</option>
                        <option name="276">GRASS</option>
                        <option name="277">Grammer</option>
                        <option name="278">Green</option>
                        <option name="279">Groovy</option>
                        <option name="280">Hack</option>
                        <option name="281">HAL/S</option>
                        <option name="282">Haskell</option>
                        <option name="283">Haxe</option>
                        <option name="284">High Level Assembly</option>
                        <option name="285">HLSL</option>
                        <option name="286">Hop</option>
                        <option name="287">Hope</option>
                        <option name="288">Hugo</option>
                        <option name="289">Hume</option>
                        <option name="290">HyperTalk</option>
                        <option name="291">IBM Basic Assembly Language (BAL)</option>
                        <option name="292">IBM Informix-4GL</option>
                        <option name="293">IBM RPG</option>
                        <option name="294">ICI</option>
                        <option name="295">Icon</option>
                        <option name="296">Id</option>
                        <option name="297">IDL (Interactive Data Language)</option>
                        <option name="298">IL</option>
                        <option name="299">IMP</option>
                        <option name="300">Inform</option>
                        <option name="301">INTERCAL</option>
                        <option name="302">Io</option>
                        <option name="303">Ioke</option>
                        <option name="304">IPL</option>
                        <option name="305">IPTSCRAE</option>
                        <option name="306">ISWIM</option>
                        <option name="307">J</option>
                        <option name="308">J#</option>
                        <option name="309">JADE</option>
                        <option name="310">Jako</option>
                        <option name="311">Jackson Structured Programming</option>
                        <option name="312">JAL</option>
                        <option name="313">Janus</option>
                        <option name="314">JASS</option>
                        <option name="315">Java</option>
                        <option name="316">JavaScript</option>
                        <option name="317">JCL (Job Control Langage)</option>
                        <option name="318">JEAN</option>
                        <option name="319">Join Java</option>
                        <option name="320">JOSS</option>
                        <option name="321">Joule</option>
                        <option name="322">JOVIAL</option>
                        <option name="323">Joy</option>
                        <option name="324">JSP</option>
                        <option name="325">Julia</option>
                        <option name="326">Kafe</option>
                        <option name="327">Kaleidoscope</option>
                        <option name="328">Karel</option>
                        <option name="329">Karel++</option>
                        <option name="330">Kaya</option>
                        <option name="331">KEE</option>
                        <option name="332">Kiev</option>
                        <option name="333">KIF</option>
                        <option name="334">Kite</option>
                        <option name="335">Kogut</option>
                        <option name="336">Korn shell (ksh)</option>
                        <option name="337">Kotlin</option>
                        <option name="338">KRC</option>
                        <option name="339">KRYPTON</option>
                        <option name="340">KUKA</option>
                        <option name="341">L</option>
                        <option name="342">L# .NET</option>
                        <option name="343">LabVIEW</option>
                        <option name="344">Ladder (LD)</option>
                        <option name="345">Lagoona</option>
                        <option name="346">LANSA</option>
                        <option name="347">LARP</option>
                        <option name="348">Lasso</option>
                        <option name="349">Lava</option>
                        <option name="350">Leadwerks Script</option>
                        <option name="351">Leda</option>
                        <option name="352">leekwars</option>
                        <option name="353">Legoscript</option>
                        <option name="354">Lexico</option>
                        <option name="355">Limbo</option>
                        <option name="356">Limnor</option>
                        <option name="357">LINC</option>
                        <option name="358">Lingo</option>
                        <option name="359">Linoleum</option>
                        <option name="360">Linotte</option>
                        <option name="361">LIS</option>
                        <option name="362">LISA</option>
                        <option name="363">Lisaac</option>
                        <option name="364">Lisp</option>
                        <option name="365">Lithe</option>
                        <option name="366">Little b</option>
                        <option name="367">Logo</option>
                        <option name="368">LOLCODE</option>
                        <option name="369">LPC</option>
                        <option name="370">LSE</option>
                        <option name="371">LSL</option>
                        <option name="372">Lua</option>
                        <option name="373">Lucid</option>
                        <option name="374">Lush</option>
                        <option name="375">Lustre</option>
                        <option name="376">LYaPAS</option>
                        <option name="377">Lynx</option>
                        <option name="378">LZX</option>
                        <option name="379">M</option>
                        <option name="380">M4</option>
                        <option name="381">Maxima</option>
                        <option name="382">MAD</option>
                        <option name="383">Magik</option>
                        <option name="384">Magma</option>
                        <option name="385">Malbolge</option>
                        <option name="386">MapBasic</option>
                        <option name="387">Maple</option>
                        <option name="388">MAPPER</option>
                        <option name="389">MARK-IV</option>
                        <option name="390">Mary</option>
                        <option name="391">Microsoft Macro Assembler</option>
                        <option name="392">Micro Lua DS</option>
                        <option name="393">Mathematica</option>
                        <option name="394">MATLAB</option>
                        <option name="395">MaxScript (Autodesk 3ds Max)</option>
                        <option name="396">Maya (MEL)</option>
                        <option name="397">MDL</option>
                        <option name="398">Mercury</option>
                        <option name="399">Mesa</option>
                        <option name="400">MetaL</option>
                        <option name="401">MicroAlg</option>
                        <option name="402">Microcode</option>
                        <option name="403">MicroScript</option>
                        <option name="404">MIIS</option>
                        <option name="405">MillScript</option>
                        <option name="406">MIMIC</option>
                        <option name="407">min</option>
                        <option name="408">MisterDev</option>
                        <option name="409">Mindscript</option>
                        <option name="410">Miranda</option>
                        <option name="411">mIRC</option>
                        <option name="412">Miva Script</option>
                        <option name="413">ML</option>
                        <option name="414">Moby</option>
                        <option name="415">Model 204</option>
                        <option name="416">Modula</option>
                        <option name="417">Modula-2</option>
                        <option name="418">Modula-3</option>
                        <option name="419">Mondrian</option>
                        <option name="420">MOO</option>
                        <option name="421">Mortran</option>
                        <option name="422">Moto</option>
                        <option name="423">Mouse</option>
                        <option name="424">MPD</option>
                        <option name="425">MPP</option>
                        <option name="426">MSIL (CIL)</option>
                        <option name="427">MSL</option>
                        <option name="428">MSX BASIC</option>
                        <option name="429">MUMPS</option>
                        <option name="430">Mythryl</option>
                        <option name="431">N</option>
                        <option name="432">Napier88</option>
                        <option name="433">Natural</option>
                        <option name="434">NBC</option>
                        <option name="435">NEAT chipset</option>
                        <option name="436">Neko</option>
                        <option name="437">Nemerle</option>
                        <option name="438">Neonitisme</option>
                        <option name="439">NESL</option>
                        <option name="440">NestJs</option>
                        <option name="441">Net.Data</option>
                        <option name="442">NetLogo</option>
                        <option name="443">NewLISP</option>
                        <option name="444">NEWP</option>
                        <option name="445">NewtonScript</option>
                        <option name="446">NGL</option>
                        <option name="447">Nial</option>
                        <option name="448">Nice</option>
                        <option name="449">Nickle</option>
                        <option name="450">Nil</option>
                        <option name="451">Nit</option>
                        <option name="452">Node.js</option>
                        <option name="453">NPL</option>
                        <option name="454">NQC</option>
                        <option name="455">Nu</option>
                        <option name="456">NXC</option>
                        <option name="457">NXT-G</option>
                        <option name="458">Nyquist</option>
                        <option name="459">o:XML</option>
                        <option name="460">Oak</option>
                        <option name="461">Oberon</option>
                        <option name="462">Object Lisp</option>
                        <option name="463">ObjectLOGO</option>
                        <option name="464">Objective-C</option>
                        <option name="465">Objective-J</option>
                        <option name="466">Obliq</option>
                        <option name="467">Obol</option>
                        <option name="468">OCaml</option>
                        <option name="469">occam</option>
                        <option name="470">occam-p</option>
                        <option name="471">OmniMark</option>
                        <option name="472">ooc</option>
                        <option name="473">Opa</option>
                        <option name="474">Opal</option>
                        <option name="475">OpenEdge ABL</option>
                        <option name="476">OPL</option>
                        <option name="477">OPS5</option>
                        <option name="478">Ork</option>
                        <option name="479">ORCA/Modula-2</option>
                        <option name="480">Orwell</option>
                        <option name="481">Oxygene</option>
                        <option name="482">Oz</option>
                        <option name="483">Panoramic</option>
                        <option name="484">PARI/GP</option>
                        <option name="485">Pascal</option>
                        <option name="486">Pascal Objet</option>
                        <option name="487">Pawn</option>
                        <option name="488">PCASTL</option>
                        <option name="489">PCF</option>
                        <option name="490">PEARL</option>
                        <option name="491">Perl</option>
                        <option name="492">Pharo</option>
                        <option name="493">PHP</option>
                        <option name="494">Phrogram</option>
                        <option name="495">Pico</option>
                        <option name="496">Pict</option>
                        <option name="497">Piet</option>
                        <option name="498">Pike</option>
                        <option name="499">PIKT</option>
                        <option name="500">PILOT</option>
                        <option name="501">Pizza</option>
                        <option name="502">Pi-calcul</option>
                        <option name="503">PL-11</option>
                        <option name="504">PL/0</option>
                        <option name="505">PL/B</option>
                        <option name="506">PL/C</option>
                        <option name="507">PL/I</option>
                        <option name="508">PL/M</option>
                        <option name="509">PL/P</option>
                        <option name="510">PL/SQL</option>
                        <option name="511">PL360</option>
                        <option name="512">PLANC</option>
                        <option name="513">Plankalkül</option>
                        <option name="514">PLEX</option>
                        <option name="515">PLEXIL</option>
                        <option name="516">Pliant</option>
                        <option name="517">POP-11</option>
                        <option name="518">Poplog</option>
                        <option name="519">Portal</option>
                        <option name="520">PostScript</option>
                        <option name="521">PortablE</option>
                        <option name="522">PowerBuilder</option>
                        <option name="523">Powerhouse</option>
                        <option name="524">PowerShell</option>
                        <option name="525">PPL</option>
                        <option name="526">Processing</option>
                        <option name="527">Prograph</option>
                        <option name="528">Progress 4GL</option>
                        <option name="529">PROIV</option>
                        <option name="530">Prolog</option>
                        <option name="531">Promela</option>
                        <option name="532">PROTEL</option>
                        <option name="533">Proteus</option>
                        <option name="534">ProvideX</option>
                        <option name="535">Pure</option>
                        <option name="536">PureBasic</option>
                        <option name="537">Python</option>
                        <option name="538">Q</option>
                        <option name="539">Q#</option>
                        <option name="540">Qi</option>
                        <option name="541">QtScript</option>
                        <option name="542">QBasic</option>
                        <option name="543">QML</option>
                        <option name="544">QuakeC</option>
                        <option name="545">QPL</option>
                        <option name="546">R</option>
                        <option name="547">R++</option>
                        <option name="548">Rapira</option>
                        <option name="549">Ratfiv</option>
                        <option name="550">Ratfor</option>
                        <option name="551">RBScript</option>
                        <option name="552">rc</option>
                        <option name="553">Rebol</option>
                        <option name="554">Red</option>
                        <option name="555">Redcode</option>
                        <option name="556">REFAL</option>
                        <option name="557">Reia</option>
                        <option name="558">Revolution</option>
                        <option name="559">REXX</option>
                        <option name="560">Rlab</option>
                        <option name="561">ROOP</option>
                        <option name="562">RPG</option>
                        <option name="563">RPL</option>
                        <option name="564">RSL</option>
                        <option name="565">RTL/2</option>
                        <option name="566">Ruby</option>
                        <option name="567">Rust</option>
                        <option name="568">S</option>
                        <option name="569">S2</option>
                        <option name="570">S3</option>
                        <option name="571">S-Lang</option>
                        <option name="572">SA-C</option>
                        <option name="573">SAC</option>
                        <option name="574">Safe C</option>
                        <option name="575">SAIL</option>
                        <option name="576">SALSA</option>
                        <option name="577">SAM76</option>
                        <option name="578">SAS</option>
                        <option name="579">SASL</option>
                        <option name="580">Sather</option>
                        <option name="581">Sawzall</option>
                        <option name="582">SBL</option>
                        <option name="583">Scala</option>
                        <option name="584">Scheme</option>
                        <option name="585">Scilab</option>
                        <option name="586">Scol</option>
                        <option name="587">Scratch</option>
                        <option name="588">Script.NET</option>
                        <option name="589">Sed</option>
                        <option name="590">Seed7</option>
                        <option name="591">Self</option>
                        <option name="592">SETL</option>
                        <option name="593">Shakespeare Programming Language</option>
                        <option name="594">Shift Script</option>
                        <option name="595">Signal</option>
                        <option name="596">SiMPLE</option>
                        <option name="597">SIMPOL</option>
                        <option name="598">SIMSCRIPT</option>
                        <option name="599">Simula</option>
                        <option name="600">SISAL</option>
                        <option name="601">Slate</option>
                        <option name="602">SLIP</option>
                        <option name="603">SMALL</option>
                        <option name="604">Smalltalk</option>
                        <option name="605">SML</option>
                        <option name="606">SNOBOL</option>
                        <option name="607">SPITBOL</option>
                        <option name="608">Snap!</option>
                        <option name="609">Snow</option>
                        <option name="610">Snowball</option>
                        <option name="611">SNUSP</option>
                        <option name="612">SOL</option>
                        <option name="613">Span</option>
                        <option name="614">SPARK</option>
                        <option name="615">Spice</option>
                        <option name="616">SPIN</option>
                        <option name="617">SP/k</option>
                        <option name="618">SPS</option>
                        <option name="619">Squeak</option>
                        <option name="620">Squirrel</option>
                        <option name="621">SR</option>
                        <option name="622">SSL</option>
                        <option name="623">STOS BASIC</option>
                        <option name="624">Strand</option>
                        <option name="625">Subtext</option>
                        <option name="626">Suneido</option>
                        <option name="627">SuperCollider</option>
                        <option name="628">Swift</option>
                        <option name="629">SYMPL</option>
                        <option name="630">SyncCharts</option>
                        <option name="631">SystemVerilog</option>
                        <option name="632">Sourcepawn</option>
                        <option name="633">T</option>
                        <option name="634">TACL</option>
                        <option name="635">TACPOL</option>
                        <option name="636">TADS</option>
                        <option name="637">TAL</option>
                        <option name="638">Tcl</option>
                        <option name="639">Tea</option>
                        <option name="640">TECO</option>
                        <option name="641">TELCOMP</option>
                        <option name="642">CA-Telon</option>
                        <option name="643">TenCORE</option>
                        <option name="644">Terra</option>
                        <option name="645">TEX</option>
                        <option name="646">TeX</option>
                        <option name="647">Ticol</option>
                        <option name="648">TIE</option>
                        <option name="649">Tiger</option>
                        <option name="650">Thue</option>
                        <option name="651">TI-Basic</option>
                        <option name="652">TI-Extended Basic</option>
                        <option name="653">Timber</option>
                        <option name="654">Tom</option>
                        <option name="655">TOM</option>
                        <option name="656">Topspeed</option>
                        <option name="657">TPU</option>
                        <option name="658">Trac</option>
                        <option name="659">Transact-SQL</option>
                        <option name="660">TTCN</option>
                        <option name="661">Turing</option>
                        <option name="662">TUTOR</option>
                        <option name="663">TXL</option>
                        <option name="664">Turbo Pascal</option>
                        <option name="665">TypeScript</option>
                        <option name="666">Ubercode</option>
                        <option name="667">Unicon</option>
                        <option name="668">Uniface</option>
                        <option name="669">uniPaaS</option>
                        <option name="670">UNITY</option>
                        <option name="671">unityscript</option>
                        <option name="672">Unix shell</option>
                        <option name="673">Unlambda</option>
                        <option name="674">UnrealScript</option>
                        <option name="675">USE</option>
                        <option name="676">V</option>
                        <option name="677">Vala</option>
                        <option name="678">VBA</option>
                        <option name="679">VBScript</option>
                        <option name="680">Verilog</option>
                        <option name="681">VHDL</option>
                        <option name="682">Visual Adélia</option>
                        <option name="683">Visual Basic (VB6)</option>
                        <option name="684">Visual Basic .NET</option>
                        <option name="685">Visual DataFlex</option>
                        <option name="686">Visual DialogScript</option>
                        <option name="687">Visual FoxPro</option>
                        <option name="688">Visual Objects</option>
                        <option name="689">Vvvv</option>
                        <option name="690">Water</option>
                        <option name="691">WATFIV, WATFOR</option>
                        <option name="692">WebQL</option>
                        <option name="693">Whitespace</option>
                        <option name="694">Winbatch</option>
                        <option name="695">WLangage (WinDev)</option>
                        <option name="696">Windows PowerShell</option>
                        <option name="697">X#</option>
                        <option name="698">X++</option>
                        <option name="699">X10</option>
                        <option name="700">XBL</option>
                        <option name="701">xHarbour</option>
                        <option name="702">XL</option>
                        <option name="703">XOTcl</option>
                        <option name="704">XPL</option>
                        <option name="705">XPL0</option>
                        <option name="706">XQuery</option>
                        <option name="707">XSLT</option>
                        <option name="708">Y</option>
                        <option name="709">YaBasic</option>
                        <option name="710">YAL</option>
                        <option name="711">Yoix</option>
                        <option name="712">Yorick</option>
                        <option name="713">Z notation</option>
                        <option name="714">Zeno</option>
                        <option name="715">Zonnon</option>
                        <option name="716">ZOPL</option>
                        <option name="717">ZPL</option>
                        <option name="718">ZZT-oop</option>
                    </select>
                </div>

            </form>

            <button type="button" onclick="submit();" class="btn btn-primary">Valider</button>

            <div id="note" class="mt-3"></div>
        </div>
        <script>
            function submit() {
                const language = document.getElementById('language');

                getHtmlContent('/includes/secret.php', 'lang=' + language.value.split('+').join('%2B')).then((res) => {
                    document.getElementById('note').innerHTML = res;
                });
            }
        </script>
    </main>

    <?php include('includes/footer.php'); ?>

</body>

</html>